# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd3124e69e395a5b2b3f879472bfb8918561e5f3203830bef055b3b449a0000582ce8e8612c8212b495c2107040953af47bd20352faf246d638c9dd9d6182e0d

test:
  secret_key_base: 39c6b2897d8b3249e7fcdd2329e4165847d46186d7652f778b119c3802dd8d877f47cc33bbe12f556850bedfae08029e90e50e0639b6a393d89a8da8b1bc3db0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
